# Generated by Django 5.0.6 on 2024-06-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/profile_pictures/avatar.png', null=True, upload_to='media/profile_pictures/'),
        ),
    ]
